on:
  pull_request:
  workflow_dispatch:

name: Test examples on Ubuntu 20.04

jobs:
  test-examples:
    name: test examples
    runs-on: [ubuntu-20.04]
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v3

      - name: Get the archive from the url.
        run: curl -fOL https://github.com/roc-lang/roc/releases/download/nightly/roc_nightly-linux_x86_64-latest.tar.gz

      - name: extract nightly roc tar
        run: tar -xf roc_nightly-linux_x86_64-latest.tar.gz

      - name: delete tar
        run: rm roc_nightly-linux_x86_64-latest.tar.gz

      - name: simplify nightly folder name
        run: mv roc_nightly* roc_nightly

      - name: get short commit SHA
        run: echo "SHORT_COMMIT_SHA=$(./roc_nightly/roc version | grep -oP 'commit \K[a-f0-9]+' )" >> $GITHUB_ENV

      - name: get roc repo for static-site-gen platform and its dependencies
        run: |
          cd roc_nightly
          find . -mindepth 1 ! -name 'roc' -exec rm -rf {} +
          mkdir gitrepo
          cd gitrepo
          git clone https://github.com/roc-lang/roc.git
          cd roc
          git checkout ${{ env.SHORT_COMMIT_SHA }}
          mv * ../../


      - name: install expect # used to check if output is correct
        run: sudo apt install -y expect

      - name: print runner CPU
        run: lscpu

      - run: ./ci_scripts/all_tests.sh

      # TODO re-enable once issue#74 is fixed
      #- run: ./roc_nightly/roc run main.roc -- examples build
      - run: ./roc_nightly/roc build main.roc
